// Load & Pallet Optimizer
// Optimize truck load and pallet configurations using bin-packing heuristics to maximize space utilization for freight logistics.
// Auto-generated by @ph-itdev/logistics-pipeline


function firstFitDecreasing(items, containerCapacity) {
  const sorted = [...items].sort((a, b) => b.weight - a.weight);
  const containers = [];
  for (const item of sorted) {
    let placed = false;
    for (const c of containers) {
      if (c.used + item.weight <= containerCapacity) { c.items.push(item); c.used += item.weight; placed = true; break; }
    }
    if (!placed) containers.push({ items: [item], used: item.weight, capacity: containerCapacity });
  }
  return containers;
}

function optimizePalletLayer(palletWidth, palletDepth, items) {
  const placed = [];
  let currentX = 0, currentY = 0, rowHeight = 0;
  for (const item of items) {
    if (currentX + item.width <= palletWidth) {
      placed.push({ ...item, x: currentX, y: currentY });
      currentX += item.width;
      rowHeight = Math.max(rowHeight, item.height || item.depth || 0);
    } else if (currentY + rowHeight + (item.height || 0) <= palletDepth) {
      currentY += rowHeight;
      currentX = 0;
      placed.push({ ...item, x: currentX, y: currentY });
      currentX += item.width;
      rowHeight = item.height || 0;
    }
  }
  const usedArea = placed.reduce((s, p) => s + p.width * (p.height || p.depth || 0), 0);
  const totalArea = palletWidth * palletDepth;
  return { placements: usedArea, totalArea, utilization: +((usedArea / totalArea) * 100).toFixed(1), placed };
}

function calculateLoadMetrics(container, { maxWeight = 45000, maxVolume = 2000 } = {}) {
  const totalWeight = container.items.reduce((s, i) => s + (i.weight || 0), 0);
  const totalVolume = container.items.reduce((s, i) => s + (i.volume || 0), 0);
  return {
    items: container.items.length,
    weight: totalWeight,
    weightUtilization: +((totalWeight / maxWeight) * 100).toFixed(1),
    volume: totalVolume,
    volumeUtilization: +((totalVolume / maxVolume) * 100).toFixed(1),
  };
}



// ─── Auto-generated utility helpers ──────────────────────────────────────────
function _logisticsHelpers() {
  return {
    timestamp: () => new Date().toISOString(),
    uuid: () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
      const r = Math.random() * 16 | 0;
      return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    }),
    sleep: (ms) => new Promise(r => setTimeout(r, ms)),
    retry: async (fn, maxAttempts = 3, delayMs = 1000) => {
      for (let i = 0; i < maxAttempts; i++) {
        try { return await fn(); } catch (e) { if (i === maxAttempts - 1) throw e; await new Promise(r => setTimeout(r, delayMs * (i + 1))); }
      }
    },
    clamp: (val, min, max) => Math.min(Math.max(val, min), max),
    chunk: (arr, size) => Array.from({ length: Math.ceil(arr.length / size) }, (_, i) => arr.slice(i * size, i * size + size)),
  };
}

module.exports = { firstFitDecreasing, optimizePalletLayer, calculateLoadMetrics };
